### ISSUE TITLE
zoom failed at docusaurus version 2.0.0-beta.18

### ISSUE THREAD

**Issue by qileq** [flexanalytics/plugin-image-zoom#11]
When I click the image, I get a error message in Chrome console:
![image](https://user-images.githubusercontent.com/94281389/160734935-d875e98d-c856-4d30-81f6-f3858cc67a5b.png)

Then I check the image html code:
![image](https://user-images.githubusercontent.com/94281389/160734989-4dc66ba4-87a1-4713-b837-8a4ccc050ac6.png)

It's seems like [refactor: extract MDX components #6989](https://github.com/facebook/docusaurus/pull/6989) modify image class name, then image zoom plugin failed.

- docusaurus: 2.0.0-beta.18
- medium-zoom: 1.0.6

**Comment by ntolia** [comment]
Ran into the same problem with Docusaurus 2.0.1. I discovered that if I remove the following medium-zoom options, the error does not occur.

```
          container: '#zoom-container',
          template: '#zoom-template',
```

**Comment by qileq** [comment]
> Ran into the same problem with Docusaurus 2.0.1. I discovered that if I remove the following medium-zoom options, the error does not occur.
> 
> ```
>           container: '#zoom-container',
>           template: '#zoom-template',
> ```

Yes, I'm success too, thank you very much! @ntolia
