### ISSUE TITLE
Extend support to support mdx pages

### ISSUE THREAD

**Issue by RudraSen2** [flexanalytics/plugin-image-zoom#12]
As far as I know, this plugin only supports images that are in docs or blog. I want to have support for the mdx pages also which are in root for example https://example.com/mdxpage should support image zoom.

**Comment by ataft** [comment]
Take a look at this MDX page from our site:
https://github.com/flexanalytics/flexit-docs/blob/master/docs/dbt.mdx

Here it is live, which you can see works fine:
https://learn.flexitanalytics.com/docs/dbt/

**Comment by RudraSen2** [comment]
But this is in docs. My images that are in the root index.js does not support zoom
