### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ruanqizhen** [flexanalytics/plugin-image-zoom#5]
There error message:
>npm install ataft/plugin-image-zoom                                                        
npm ERR! code ENOENT                                                                                                    
npm ERR! syscall spawn git                                                                                              
npm ERR! path git                                                                                                       
npm ERR! errno -4058                                                                                                    
npm ERR! enoent An unknown git error occurred                                                                           
npm ERR! enoent This is related to npm not being able to find a file.                                                   
npm ERR! enoent

**Comment by ataft** [comment]
Oops, the repository owner changed and the old link did not persist. Try the following:
`npm install flexanalytics/plugin-image-zoom`

**Comment by ruanqizhen** [comment]
> npm install flexanalytics/plugin-image-zoom

I tried this too, but it had the same error:

>   > npm install flexanalytics/plugin-image-zoom                                                
npm ERR! code ENOENT                                                                                                    
npm ERR! syscall spawn git                                                                                              
npm ERR! path git                                                                                                       
npm ERR! errno -4058                                                                                                    
npm ERR! enoent An unknown git error occurred                                                                           
npm ERR! enoent This is related to npm not being able to find a file.                                                   
npm ERR! enoent

**Comment by ataft** [comment]
Oh, I see, perhaps this is the same as issue #4 where Git client was not installed

Otherwise, perhaps this thread helps: https://stackoverflow.com/questions/49620780/cant-install-any-npm-package-error-4058

After that, I'm at a loss for what's going on. It appears to be a local problem, as this works fine for me and others

**Comment by ruanqizhen** [comment]
> Oh, I see, perhaps this is the same as issue #4 where Git client was not installed
> 
> Otherwise, perhaps this thread helps: https://stackoverflow.com/questions/49620780/cant-install-any-npm-package-error-4058
> 
> After that, I'm at a loss for what's going on. It appears to be a local problem, as this works fine for me and others

Looks like neither of them were my problem.  I've installed git client, no other process are running.
I have installed many packages with npm, but only this one got the error.

**Comment by ataft** [comment]
Hmm, maybe this due to the install being from a github repository. I'll reopen the issue in case someone else runs into it and can help here.

**Comment by ruanqizhen** [comment]
I found the problem, I think this is because the git client I installed was not the right one.  After installing a version I downloaded from "https://git-scm.com/download/win", I was able to install it on my own machine.

However, it still couldn't work on Vercel.  I'm using Vercel to deploy my doc built with Docusaurus.  There error message is listed below:

```
19:03:08.920 | Build cache downloaded [90.05 MB]: 3246.323ms
19:03:09.562 | Detected package.json
19:03:09.562 | Installing dependencies...
19:03:09.802 | yarn install v1.22.17
19:03:09.876 | [1/4] Resolving packages...
19:03:10.520 | [2/4] Fetching packages...
19:03:23.988 | error Command failed.
19:03:23.988 | Exit code: 128
19:03:23.988 | Command: git
19:03:23.988 | Arguments: ls-remote --tags --heads ssh://git@github.com/flexanalytics/plugin-image-zoom.git
19:03:23.988 | Directory: /vercel/path0
19:03:23.988 | Output:
19:03:23.989 | Host key verification failed.
19:03:23.989 | fatal: Could not read from remote repository.
19:03:23.989 |  
19:03:23.989 | Please make sure you have the correct access rights
19:03:23.989 | and the repository exists.
19:03:23.990 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
19:03:24.435 | Error: Command "yarn install" exited with 128
```

**Comment by ataft** [comment]
Hmm, maybe github.com needs to be an authorized host in your vercel environment. Perhaps one of the following helps:
- https://stackoverflow.com/a/29380765/5551593
- https://stackoverflow.com/questions/15214977/cloning-git-repo-causes-error-host-key-verification-failed-fatal-the-remote/29380672#29380672

**Comment by ataft** [comment]
Looks like issue #6 is similar to your "Host key verification failed" issue. Closing this issue, let's move the dialogue over there.
