### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by macOSWk** [flexanalytics/plugin-image-zoom#6]
> yarn install 

o There appears to be trouble with your network connection. Retrying...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/flexanalytics/plugin-image-zoom.git
Directory: /Users/mac/test/awesometic-docs
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

The process has ended, the exit code is 128

**Comment by ataft** [comment]
Done: https://www.npmjs.com/package/plugin-image-zoom

Does this solve this issue?

**Comment by ataft** [comment]
Published to NPM
