### ISSUE TITLE
How to change background color

### ISSUE THREAD

**Issue by AlbinoGazelle** [flexanalytics/plugin-image-zoom#7]
How can I change the background color when zooming? My website is a darker theme and would love to get rid of the white background?

Thanks.

Not zoomed:
![image](https://user-images.githubusercontent.com/37495851/149445210-aaf69020-7319-459f-afc7-46fcf05af969.png)

Zoomed: 
![image](https://user-images.githubusercontent.com/37495851/149445244-9bceafa1-d721-48cc-8b27-583decbec519.png)

**Comment by ataft** [comment]
This is controlled by css in the `medium-zoom` plugin. Use the `medium-zoom-overlay` class, as shown here:

```
.medium-zoom--opened .medium-zoom-overlay {
    background: green !important;
}

```
![image](https://user-images.githubusercontent.com/11670864/149555341-5e2cadde-1621-4fd2-af7c-7174b1513cd6.png)
